import React, { createContext, useContext, useMemo, useState } from "react";

const STORAGE_KEY = "cropplan_language";

const translations = {
  en: {
    nav: {
      home: "Home",
      aboutUs: "About Us",
      login: "Login",
      register: "Register",
      adminDashboard: "Admin Dashboard",
      farmerDashboard: "Farmer Dashboard",
      language: "Language",
      switchLanguage: "Switch Language",
      viewProfile: "View Profile",
      admin: "Admin",
    },
    profile: {
      title: "My Profile",
      subtitle: "Manage your personal information and account settings",
      personalDetails: "Personal Information",
      accountStatus: "Account Status",
      verifiedDesc: "Your account is verified and active",
    },
    home: {
      title: "DEMAND BASED CROP PLANNING SYSTEM",
      subtitle: "To Reduce Agricultural Surplus Through Market Integration",
    },
    aboutProject: {
      title: "About This Platform",
      missionTitle: "Our Mission",
      missionText:
        "We aim to bridge the gap between farmers and markets by providing a demand-based crop planning system. Our platform helps farmers make informed decisions about what to grow, reducing agricultural surplus and ensuring better market prices for their produce.",
      marketAnalysisTitle: "Market Analysis",
      marketAnalysisText:
        "Real-time market data and demand forecasting to help farmers plan their crops effectively.",
      betterPricingTitle: "Better Pricing",
      betterPricingText:
        "Connect directly with buyers and get fair prices for your produce without middlemen.",
      communitySupportTitle: "Community Support",
      communitySupportText:
        "Join a community of farmers and experts to share knowledge and best practices.",
      visionTitle: "Our Vision",
      visionText:
        "To create a sustainable agricultural ecosystem where farmers prosper by growing what the market needs. We envision a future where agricultural waste is minimized, farmer incomes are maximized, and food security is ensured for all.",
    },
    aboutUs: {
      title: "Meet Our Team",
      subtitle:
        "We are a passionate team of developers dedicated to revolutionizing agriculture through technology.",
      fullStackDeveloper: "Full Stack Developer",
      backendDeveloper: "Backend Developer",
      frontendDeveloper: "Frontend Developer",
      mernDesigner: "MERN Stack Developer & Designer",
      scalableSolutions: "Passionate about building scalable solutions",
      apiExpert: "Expert in APIs and database systems",
      beautifulUx: "Crafting beautiful user experiences",
      seamlessExperience: "Creating seamless full-stack experiences",
      quote: '"Plan smarter. Grow better. Harvest success."',
      quoteAuthor: "- CropPlan Team",
      whyProjectTitle: "Why This Project?",
      whyProjectText:
        "We saw farmers struggling with market unpredictability. Technology can bridge this gap and create sustainable farming practices.",
      visionCardTitle: "Our Vision",
      visionCardText:
        "A future where every farmer has access to market insights, reducing waste and maximizing their earnings for a sustainable tomorrow.",
      techStackTitle: "Our Tech Stack",
      techStackText:
        "Built with MongoDB, Express, React and Node.js, the MERN stack powering modern, scalable web applications.",
      togetherTitle: "Together We Build",
      togetherText:
        "Four minds, one mission, to revolutionize how farmers plan their crops by connecting them with real-time market demand.",
      tagSustainable: "Sustainable Farming",
      tagInsights: "Data-Driven Insights",
      tagFarmerFirst: "Farmer-First Approach",
    },
    login: {
      welcomeBack: "Welcome Back",
      continueText: "Sign in to continue to CropPlan",
      emailOrMobile: "Email or Mobile Number",
      emailOrMobilePlaceholder: "you@example.com or 9876543210",
      password: "Password",
      rememberMe: "Remember me",
      signIn: "Sign In",
      noAccount: "Don't have an account?",
      createAccount: "Create Account",
      brandText: "CropPlan - Smart Farming Solutions",
      failed: "Login failed",
    },
    register: {
      successTitle: "Registration Successful!",
      successText:
        "You have registered successfully. Please wait for the admin approval. We will notify you via email once your account is approved.",
      pendingApproval: "Pending Admin Approval",
      backToLogin: "Back to Login",
      createAccount: "Create Account",
      joinText: "Join CropPlan to start planning smarter",
      fullName: "Full Name",
      fullNamePlaceholder: "John Doe",
      emailAddress: "Email Address",
      emailPlaceholder: "you@example.com",
      phoneNumber: "Phone Number",
      phonePlaceholder: "+91 98765 43210",
      address: "Address",
      addressPlaceholder: "Enter your full address",
      createPassword: "Create Password",
      registerButton: "Register",
      alreadyAccount: "Already have an account?",
      signIn: "Sign In",
      brandText: "CropPlan - Smart Farming Solutions",
      failed: "Registration failed. Please try again.",
      profileImage: "Profile Photo",
      photoPreview: "Photo preview",
      addPhoto: "Add photo",
      uploadImage: "Upload Image",
      takePhoto: "Take Photo",
      capture: "Capture",
      cancel: "Cancel",
      remove: "Remove",
      imageOptional:
        "Upload or capture a profile photo to complete your profile",
      invalidImageFile: "Please select a valid image file",
      cameraAccessDenied: "Failed to access camera",
      errorNoImage: "Please upload or capture a profile photo",
      errorUploadFailed: "Failed to upload image. Please try again.",
      imageUploadFailed: "Failed to upload image. Please try again.",
      profileTitle: "Set Your Profile Photo",
      profileSubtitle: "Take or upload a picture to continue",
      uploading: "Uploading...",
      processing: "Processing...",
      continue: "Continue to Registration",
      preview: "Profile Preview",
      changePhoto: "Change Photo",
      yourName: "Your Name",
      farmerRole: "Farmer",
      yourAddress: "Your Address will appear here",
    },
    admin: {
      title: "Admin Dashboard",
      pendingUsers: "Pending Users",
      allUsers: "All Users",
      approvedUsers: "Approved Users",
      marketDemands: "Market Demands",
      approve: "Approve",
      reject: "Reject",
      approved: "Approved",
      rejected: "Rejected",
      pending: "Pending",
      name: "Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      role: "Role",
      status: "Status",
      actions: "Actions",
      noPendingUsers: "No pending users",
      noUsers: "No users found",
      addMarketDemand: "Add Market Demand",
      crop: "Crop",
      region: "Region",
      demandLevel: "Demand Level",
      season: "Season",
      quantity: "Quantity",
      quantityUnit: "Unit",
      price: "Price",
      image: "Image",
      submit: "Submit",
      low: "Low",
      medium: "Medium",
      high: "High",
      kg: "kg",
      quintal: "Quintal",
      ton: "Ton",
      selectImage: "Select Image",
      uploading: "Uploading...",
      success: "Success",
      error: "Error",
      demandAdded: "Market demand added successfully",
      failedToAdd: "Failed to add market demand",
      failedToApprove: "Failed to approve user",
      failedToReject: "Failed to reject user",
      userApproved: "User approved successfully",
      userRejected: "User rejected successfully",
      delete: "Delete",
    },
    farmer: {
      welcome: "Welcome",
      manageFarm: "Manage your farm activities and crops",
      logout: "Logout",
      marketDemand: "Market Demand",
      latestDemand: "Latest demand shared by admin",
      refresh: "Refresh",
      loadingDemand: "Loading market demand...",
      noDemand: "No market demand available right now.",
      noImage: "No image available",
      crop: "Crop",
      region: "Region",
      demandLevel: "Demand Level",
      season: "Season",
      quantity: "Quantity",
      price: "Price",
      revenueGenerate: "Generate Revenue Estimate",
      accountInfo: "Account Information",
      nameLabel: "Name",
      emailLabel: "Email",
      phoneLabel: "Phone",
      addressLabel: "Address",
      seasonLabel: "Season",
      quantityLabel: "Quantity",
      pricePerUnit: "Price Per Unit",
      regionLabel: "Region",
      estimateRevenue: "Estimate Revenue for This Crop",
    },
  },
  te: {
    nav: {
      home: "హోమ్",
      aboutUs: "మా గురించి",
      login: "లాగిన్",
      register: "నమోదు",
      adminDashboard: "అడ్మిన్ డ్యాష్‌బోర్డ్",
      farmerDashboard: "రైతు డ్యాష్‌బోర్డ్",
      language: "భాష",
      switchLanguage: "భాషను మార్చండి",
      viewProfile: "ప్రొఫైల్ చూడండి",
      admin: "అడ్మిన్",
    },
    profile: {
      title: "నా ప్రొఫైల్",
      subtitle: "మీ వ్యక్తిగత సమాచారం మరియు ఖాతా సెట్టింగ్‌లను నిర్వహించండి",
      personalDetails: "వ్యక్తిగత సమాచారం",
      accountStatus: "ఖాతా స్థితి",
      verifiedDesc: "మీ ఖాతా ధృవీకరించబడింది మరియు సక్రియంగా ఉంది",
    },
    home: {
      title: "డిమాండ్ ఆధారిత పంట ప్రణాళిక వ్యవస్థ",
      subtitle: "మార్కెట్ సమన్వయం ద్వారా వ్యవసాయ అదనాన్ని తగ్గించడానికి",
    },
    aboutProject: {
      title: "ఈ ప్లాట్‌ఫారమ్ గురించి",
      missionTitle: "మా లక్ష్యం",
      missionText:
        "డిమాండ్ ఆధారిత పంట ప్రణాళిక వ్యవస్థ ద్వారా రైతులు మరియు మార్కెట్ల మధ్య అంతరాన్ని తగ్గించడం మా లక్ష్యం. ఏ పంట వేయాలి అన్న నిర్ణయంలో రైతులకు సహాయం చేస్తూ, అధిక ఉత్పత్తి తగ్గించి, మంచి ధరలు పొందేలా చేస్తాము.",
      marketAnalysisTitle: "మార్కెట్ విశ్లేషణ",
      marketAnalysisText:
        "రియల్ టైమ్ మార్కెట్ డేటా మరియు డిమాండ్ అంచనాలతో రైతులు పంటలను సమర్థంగా ప్రణాళిక చేసుకోగలరు.",
      betterPricingTitle: "మెరుగైన ధరలు",
      betterPricingText:
        "మధ్యవర్తుల లేకుండా కొనుగోలుదారులతో నేరుగా కలసి, మీ ఉత్పత్తికి న్యాయమైన ధర పొందండి.",
      communitySupportTitle: "సముదాయ మద్దతు",
      communitySupportText:
        "రైతులు మరియు నిపుణుల సమాజంతో కలసి జ్ఞానం మరియు ఉత్తమ విధానాలను పంచుకోండి.",
      visionTitle: "మా దృష్టి",
      visionText:
        "మార్కెట్ అవసరాలకు అనుగుణంగా పంటలు పండించి రైతులు అభివృద్ధి చెందే స్థిరమైన వ్యవసాయ వ్యవస్థను నిర్మించడం మా దృష్టి. వ్యవసాయ వ్యర్థం తగ్గి, రైతుల ఆదాయం పెరిగి, అందరికీ ఆహార భద్రత లభించే భవిష్యత్తు మా లక్ష్యం.",
    },
    aboutUs: {
      title: "మా బృందాన్ని కలుసుకోండి",
      subtitle:
        "సాంకేతికత ద్వారా వ్యవసాయాన్ని మార్పు చేయాలనే లక్ష్యంతో పనిచేసే అభిరుచి గల డెవలపర్ల బృందం మేము.",
      fullStackDeveloper: "ఫుల్ స్టాక్ డెవలపర్",
      backendDeveloper: "బ్యాక్‌ఎండ్ డెవలపర్",
      frontendDeveloper: "ఫ్రంట్‌ఎండ్ డెవలపర్",
      mernDesigner: "MERN స్టాక్ డెవలపర్ & డిజైనర్",
      scalableSolutions: "విస్తరించగల పరిష్కారాల నిర్మాణంపై ఆసక్తి",
      apiExpert: "APIs మరియు డేటాబేస్ వ్యవస్థల్లో నిపుణుడు",
      beautifulUx: "అందమైన యూజర్ అనుభవాల సృష్టి",
      seamlessExperience: "సులభమైన ఫుల్ స్టాక్ అనుభవాల నిర్మాణం",
      quote: '"తెలివిగా ప్రణాళిక చేయండి. మెరుగ్గా పెంచండి. విజయాన్ని కోయండి."',
      quoteAuthor: "- CropPlan బృందం",
      whyProjectTitle: "ఈ ప్రాజెక్ట్ ఎందుకు?",
      whyProjectText:
        "మార్కెట్ అనిశ్చితితో రైతులు ఇబ్బంది పడుతున్నారని చూశాం. ఈ అంతరాన్ని సాంకేతికతతో తగ్గించి, స్థిరమైన వ్యవసాయ పద్ధతులు సృష్టించవచ్చు.",
      visionCardTitle: "మా దృష్టి",
      visionCardText:
        "ప్రతి రైతుకూ మార్కెట్ సమాచారం అందుబాటులో ఉండే, వ్యర్థం తగ్గి, ఆదాయం పెరిగే స్థిరమైన భవిష్యత్తు.",
      techStackTitle: "మా టెక్ స్టాక్",
      techStackText:
        "MongoDB, Express, React, Node.js తో నిర్మించిన MERN స్టాక్ ఆధునిక, విస్తరించగల వెబ్ యాప్‌లకు బలం ఇస్తుంది.",
      togetherTitle: "కలిసి మేము నిర్మిస్తున్నాం",
      togetherText:
        "నాలుగు మేధస్సులు, ఒకే లక్ష్యం - రియల్ టైమ్ మార్కెట్ డిమాండ్‌తో రైతుల పంట ప్రణాళికను మార్చడం.",
      tagSustainable: "స్థిరమైన వ్యవసాయం",
      tagInsights: "డేటా ఆధారిత విశ్లేషణలు",
      tagFarmerFirst: "రైతు ముందుగా",
    },
    login: {
      welcomeBack: "తిరిగి స్వాగతం",
      continueText: "CropPlan కొనసాగించడానికి సైన్ ఇన్ చేయండి",
      emailOrMobile: "ఈమెయిల్ లేదా మొబైల్ నంబర్",
      emailOrMobilePlaceholder: "you@example.com లేదా 9876543210",
      password: "పాస్‌వర్డ్",
      rememberMe: "నన్ను గుర్తుంచుకోండి",
      signIn: "సైన్ ఇన్",
      noAccount: "ఖాతా లేదా?",
      createAccount: "ఖాతా సృష్టించండి",
      brandText: "CropPlan - స్మార్ట్ వ్యవసాయ పరిష్కారాలు",
      failed: "లాగిన్ విఫలమైంది",
    },
    register: {
      successTitle: "నమోదు విజయవంతమైంది!",
      successText:
        "మీ నమోదు విజయవంతంగా పూర్తైంది. అడ్మిన్ ఆమోదం కోసం వేచి ఉండండి. మీ ఖాతా ఆమోదించబడిన తర్వాత ఈమెయిల్ ద్వారా తెలియజేస్తాము.",
      pendingApproval: "అడ్మిన్ ఆమోదం పెండింగ్‌లో ఉంది",
      backToLogin: "లాగిన్‌కు తిరుగు",
      createAccount: "ఖాతా సృష్టించండి",
      joinText: "తెలివిగా ప్రణాళిక మొదలుపెట్టడానికి CropPlan లో చేరండి",
      fullName: "పూర్తి పేరు",
      fullNamePlaceholder: "జాన్ డో",
      emailAddress: "ఈమెయిల్ చిరునామా",
      emailPlaceholder: "you@example.com",
      phoneNumber: "ఫోన్ నంబర్",
      phonePlaceholder: "+91 98765 43210",
      address: "చిరునామా",
      addressPlaceholder: "మీ పూర్తి చిరునామాను నమోదు చేయండి",
      createPassword: "పాస్‌వర్డ్ సృష్టించండి",
      registerButton: "నమోదు",
      alreadyAccount: "ఇప్పటికే ఖాతా ఉందా?",
      signIn: "సైన్ ఇన్",
      brandText: "CropPlan - స్మార్ట్ వ్యవసాయ పరిష్కారాలు",
      failed: "నమోదు విఫలమైంది. మళ్లీ ప్రయత్నించండి.",
      profileImage: "ప్రొఫైల్ ఫోటో",
      photoPreview: "ఫోటో ప్రివ్యూ",
      addPhoto: "ఫోటో జోడించండి",
      uploadImage: "చిత్రం అప్‌లోడ్ చేయండి",
      takePhoto: "ఫోటో తీయండి",
      capture: "క్యాప్చర్",
      cancel: "రద్దు చేయండి",
      remove: "తీసివేయండి",
      imageOptional:
        "మీ ప్రొఫైల్‌ను పూర్తి చేయడానికి ప్రొఫైల్ ఫోటోను అప్‌లోడ్ లేదా సంగ్రహించండి",
      invalidImageFile: "దయచేసి చెల్లుబాటు అయ్యే చిత్ర ఫైలును ఎంచుకోండి",
      cameraAccessDenied: "కెమెరాకు ప్రాప్యత వైఫల్యమైంది",
      errorNoImage: "దయచేసి ప్రొఫైల్ ఫోటోను అప్‌లోడ్ చేయండి లేదా తీయండి",
      errorUploadFailed: "చిత్రాన్ని అప్‌లోడ్ చేయడం విఫలమైంది. మళ్లీ ప్రయత్నించండి.",
      imageUploadFailed: "చిత్రాన్ని అప్‌లోడ్ చేయడం విఫలమైంది. మళ్లీ ప్రయత్నించండి.",
      profileTitle: "ప్రొఫైల్ ఫోటోను సెట్ చేయండి",
      profileSubtitle: "కొనసాగించడానికి చిత్రాన్ని తీయండి లేదా అప్‌లోడ్ చేయండి",
      uploading: "అప్‌లోడ్ అవుతోంది...",
      processing: "ప్రాసెసింగ్ అవుతోంది...",
      continue: "నమోదుకు కొనసాగండి",
      preview: "ప్రొఫైల్ ప్రివ్యూ",
      changePhoto: "ఫోటో మార్చండి",
      yourName: "మీ పేరు",
      farmerRole: "రైతు",
      yourAddress: "మీ చిరునామా ఇక్కడ కనిపిస్తుంది",
    },
    admin: {
      title: "అడ్మిన్ డ్యాష్‌బోర్డ్",
      pendingUsers: "పెండింగ్ యూజర్లు",
      allUsers: "అన్ని యూజర్లు",
      approvedUsers: "ఆమోదించబడిన యూజర్లు",
      marketDemands: "మార్కెట్ డిమాండ్‌లు",
      approve: "ఆమోదించు",
      reject: "తిరస్కరించు",
      approved: "ఆమోదించబడింది",
      rejected: "తిరస్కరించబడింది",
      pending: "పెండింగ్",
      name: "పేరు",
      email: "ఈమెయిల్",
      phone: "ఫోన్",
      address: "చిరునామా",
      role: "పాత్ర",
      status: "స్థితి",
      actions: "చర్యలు",
      noPendingUsers: "పెండింగ్ యూజర్లు లేరు",
      noUsers: "యూజర్లు కనుగొనబడలేదు",
      addMarketDemand: "మార్కెట్ డిమాండ్ జోడించు",
      crop: "పంట",
      region: "ప్రాంతం",
      demandLevel: "డిమాండ్ స్థాయి",
      season: "కాలం",
      quantity: "పరిమాణం",
      quantityUnit: "యూనిట్",
      price: "ధర",
      image: "చిత్రం",
      submit: "సబ్మిట్",
      low: "తక్కువ",
      medium: "మధ్యస్థం",
      high: "అధికం",
      kg: "కిలో",
      quintal: "క్వింటల్",
      ton: "టన్",
      selectImage: "చిత్రం ఎంచుకోండి",
      uploading: "అప్‌లోడ్ అవుతోంది...",
      success: "విజయం",
      error: "లోపం",
      demandAdded: "మార్కెట్ డిమాండ్ విజయవంతంగా జోడించబడింది",
      failedToAdd: "మార్కెట్ డిమాండ్ జోడించడంలో విఫలమైంది",
      failedToApprove: "యూజర్‌ను ఆమోదించడంలో విఫలమైంది",
      failedToReject: "యూజర్‌ను తిరస్కరించడంలో విఫలమైంది",
      userApproved: "యూజర్ విజయవంతంగా ఆమోదించబడ్డారు",
      userRejected: "యూజర్ తిరస్కరించబడ్డారు",
      delete: "తొలగించు",
    },
    farmer: {
      welcome: "స్వాగతం",
      manageFarm: "మీ వ్యవసాయ కార్యకలాపాలు మరియు పంటలను నిర్వహించండి",
      logout: "లాగౌట్",
      marketDemand: "మార్కెట్ డిమాండ్",
      latestDemand: "అడ్మిన్ ద్వారా పంచబడిన తాజా డిమాండ్",
      refresh: "రిఫ్రెష్",
      loadingDemand: "మార్కెట్ డిమాండ్ లోడ్ అవుతోంది...",
      noDemand: "ప్రస్తుతం మార్కెట్ డిమాండ్ అందుబాటులో లేదు.",
      noImage: "చిత్రం అందుబాటులో లేదు",
      crop: "పంట",
      region: "ప్రాంతం",
      demandLevel: "డిమాండ్ స్థాయి",
      season: "కాలం",
      quantity: "పరిమాణం",
      price: "ధర",
      revenueGenerate: "రెవెన్యూ అంచనా రూపొందించు",
      accountInfo: "ఖాతా సమాచారం",
      nameLabel: "పేరు",
      emailLabel: "ఈమెయిల్",
      phoneLabel: "ఫోన్",
      addressLabel: "చిరునామా",
      seasonLabel: "కాలం",
      quantityLabel: "పరిమాణం",
      pricePerUnit: "యూనిట్ ధర",
      regionLabel: "ప్రాంతం",
      estimateRevenue: "ఈ పంట కోసం రెవెన్యూ అంచనా",
    },
  },
  hi: {
    nav: {
      home: "होम",
      aboutUs: "हमारे बारे में",
      login: "लॉगिन",
      register: "रजिस्टर",
      adminDashboard: "एडमिन डैशबोर्ड",
      farmerDashboard: "किसान डैशबोर्ड",
      language: "भाषा",
      switchLanguage: "भाषा बदलें",
      viewProfile: "प्रोफ़ाइल देखें",
      admin: "एडमिन",
    },
    profile: {
      title: "मेरी प्रोफ़ाइल",
      subtitle: "अपनी व्यक्तिगत जानकारी और खाता सेटिंग्स प्रबंधित करें",
      personalDetails: "व्यक्तिगत जानकारी",
      accountStatus: "खात की स्थिति",
      verifiedDesc: "आपका खाता सत्यापित और सक्रिय है",
    },
    home: {
      title: "मांग आधारित फसल योजना प्रणाली",
      subtitle: "बाजार एकीकरण के माध्यम से कृषि अधिशेष को कम करने के लिए",
    },
    aboutProject: {
      title: "इस प्लेटफॉर्म के बारे में",
      missionTitle: "हमारा मिशन",
      missionText:
        "मांग आधारित फसल योजना प्रणाली के माध्यम से किसानों और बाजार के बीच की दूरी कम करना हमारा लक्ष्य है। यह प्लेटफॉर्म किसानों को क्या उगाना है इस पर सही निर्णय लेने में मदद करता है, जिससे कृषि अधिशेष कम होता है और बेहतर कीमत मिलती है।",
      marketAnalysisTitle: "बाजार विश्लेषण",
      marketAnalysisText:
        "रियल-टाइम बाजार डेटा और मांग पूर्वानुमान किसानों को प्रभावी योजना बनाने में मदद करते हैं।",
      betterPricingTitle: "बेहतर मूल्य",
      betterPricingText:
        "बिचौलियों के बिना खरीदारों से सीधे जुड़ें और अपनी उपज का उचित मूल्य पाएं।",
      communitySupportTitle: "समुदाय सहयोग",
      communitySupportText:
        "किसानों और विशेषज्ञों के समुदाय से जुड़ें और ज्ञान व सर्वोत्तम प्रथाएं साझा करें।",
      visionTitle: "हमारा विजन",
      visionText:
        "ऐसा टिकाऊ कृषि तंत्र बनाना जहां किसान बाजार की जरूरत के अनुसार उगाकर समृद्ध हों। हम ऐसा भविष्य देखते हैं जहां कृषि अपशिष्ट कम हो, किसानों की आय बढ़े और सभी के लिए खाद्य सुरक्षा सुनिश्चित हो।",
    },
    aboutUs: {
      title: "हमारी टीम से मिलें",
      subtitle:
        "हम डेवलपर्स की एक उत्साही टीम हैं जो तकनीक के माध्यम से कृषि में बदलाव लाने के लिए समर्पित है।",
      fullStackDeveloper: "फुल स्टैक डेवलपर",
      backendDeveloper: "बैकएंड डेवलपर",
      frontendDeveloper: "फ्रंटएंड डेवलपर",
      mernDesigner: "MERN स्टैक डेवलपर और डिज़ाइनर",
      scalableSolutions: "स्केलेबल समाधान बनाने के प्रति उत्साही",
      apiExpert: "APIs और डेटाबेस सिस्टम के विशेषज्ञ",
      beautifulUx: "सुंदर उपयोगकर्ता अनुभव तैयार करना",
      seamlessExperience: "स्मूद फुल-स्टैक अनुभव बनाना",
      quote: '"बेहतर योजना बनाओ। बेहतर उगाओ। सफलता पाओ।"',
      quoteAuthor: "- CropPlan टीम",
      whyProjectTitle: "यह प्रोजेक्ट क्यों?",
      whyProjectText:
        "हमने किसानों को बाजार की अनिश्चितता से जूझते देखा। तकनीक इस अंतर को कम कर सकती है और टिकाऊ खेती को बढ़ावा दे सकती है।",
      visionCardTitle: "हमारा विजन",
      visionCardText:
        "ऐसा भविष्य जहां हर किसान को बाजार की जानकारी मिले, अपव्यय घटे और आय बढ़े।",
      techStackTitle: "हमारा टेक स्टैक",
      techStackText:
        "MongoDB, Express, React और Node.js पर बना MERN स्टैक आधुनिक और स्केलेबल वेब ऐप्स को शक्ति देता है।",
      togetherTitle: "मिलकर हम बनाते हैं",
      togetherText:
        "चार दिमाग, एक मिशन - रियल-टाइम बाजार मांग से किसानों की फसल योजना को बदलना।",
      tagSustainable: "टिकाऊ खेती",
      tagInsights: "डेटा-आधारित इनसाइट्स",
      tagFarmerFirst: "किसान-प्रथम दृष्टिकोण",
    },
    login: {
      welcomeBack: "वापसी पर स्वागत है",
      continueText: "CropPlan जारी रखने के लिए साइन इन करें",
      emailOrMobile: "ईमेल या मोबाइल नंबर",
      emailOrMobilePlaceholder: "you@example.com या 9876543210",
      password: "पासवर्ड",
      rememberMe: "मुझे याद रखें",
      signIn: "साइन इन",
      noAccount: "क्या आपका अकाउंट नहीं है?",
      createAccount: "अकाउंट बनाएं",
      brandText: "CropPlan - स्मार्ट खेती समाधान",
      failed: "लॉगिन विफल हुआ",
    },
    register: {
      successTitle: "रजिस्ट्रेशन सफल हुआ!",
      successText:
        "आपका पंजीकरण सफल हुआ। कृपया एडमिन अनुमोदन की प्रतीक्षा करें। अकाउंट स्वीकृत होने पर हम आपको ईमेल से सूचित करेंगे।",
      pendingApproval: "एडमिन अनुमोदन लंबित",
      backToLogin: "लॉगिन पर वापस जाएं",
      createAccount: "अकाउंट बनाएं",
      joinText: "स्मार्ट योजना शुरू करने के लिए CropPlan से जुड़ें",
      fullName: "पूरा नाम",
      fullNamePlaceholder: "जॉन डो",
      emailAddress: "ईमेल पता",
      emailPlaceholder: "you@example.com",
      phoneNumber: "फोन नंबर",
      phonePlaceholder: "+91 98765 43210",
      address: "पता",
      addressPlaceholder: "अपना पूरा पता लिखें",
      createPassword: "पासवर्ड बनाएं",
      registerButton: "रजिस्टर",
      alreadyAccount: "क्या पहले से अकाउंट है?",
      signIn: "साइन इन",
      brandText: "CropPlan - स्मार्ट खेती समाधान",
      failed: "रजिस्ट्रेशन विफल हुआ। कृपया फिर कोशिश करें।",
      profileImage: "प्रोफाइल फोटो",
      photoPreview: "फोटो पूर्वावलोकन",
      addPhoto: "फोटो जोड़ें",
      uploadImage: "छवि अपलोड करें",
      takePhoto: "फोटो लें",
      capture: "कैप्चर",
      cancel: "रद्द करें",
      remove: "हटाएं",
      imageOptional:
        "अपनी प्रोफाइल पूरी करने के लिए प्रोफाइल फोटो अपलोड या कैप्चर करें",
      invalidImageFile: "कृपया एक वैध छवि फाइल चुनें",
      cameraAccessDenied: "कैमरे तक पहुंच विफल",
      errorNoImage: "कृपया एक प्रोफ़ाइल फ़ोटो अपलोड करें या लें",
      errorUploadFailed: "छवि अपलोड करने में विफल। कृपया पुन: प्रयास करें।",
      imageUploadFailed: "छवि अपलोड करने में विफल। कृपया पुन: प्रयास करें।",
      profileTitle: "अपनी प्रोफाइल फोटो सेट करें",
      profileSubtitle: "जारी रखने के लिए एक फोटो लें या अपलोड करें",
      uploading: "अपलोड हो रहा है...",
      processing: "प्रोसेसिंग हो रहा है...",
      continue: "पंजीकरण के लिए जारी रखें",
      preview: "प्रोफाइल पूर्वावलोकन",
      changePhoto: "फोटो बदलें",
      yourName: "आपका नाम",
      farmerRole: "किसान",
      yourAddress: "आपका पता यहां दिखाई देगा",
    },
    admin: {
      title: "एडमिन डैशबोर्ड",
      pendingUsers: "लंबित उपयोगकर्ता",
      allUsers: "सभी उपयोगकर्ता",
      approvedUsers: "स्वीकृत उपयोगकर्ता",
      marketDemands: "बाजार मांग",
      approve: "स्वीकृत करें",
      reject: "अस्वीकार करें",
      approved: "स्वीकृत",
      rejected: "अस्वीकारित",
      pending: "लंबित",
      name: "नाम",
      email: "ईमेल",
      phone: "फोन",
      address: "पता",
      role: "भूमिका",
      status: "स्थिति",
      actions: "क्रियाएं",
      noPendingUsers: "कोई लंबित उपयोगकर्ता नहीं",
      noUsers: "कोई उपयोगकर्ता नहीं मिला",
      addMarketDemand: "बाजार मांग जोड़ें",
      crop: "फसल",
      region: "क्षेत्र",
      demandLevel: "मांग स्तर",
      season: "मौसम",
      quantity: "मात्रा",
      quantityUnit: "इकाई",
      price: "मूल्य",
      image: "छवि",
      submit: "सबमिट करें",
      low: "कम",
      medium: "मध्यम",
      high: "उच्च",
      kg: "किलोग्राम",
      quintal: "क्विंटल",
      ton: "टन",
      selectImage: "छवि चुनें",
      uploading: "अपलोड हो रहा है...",
      success: "सफलता",
      error: "त्रुटि",
      demandAdded: "बाजार मांग सफलतापूर्वक जोड़ी गई",
      failedToAdd: "बाजार मांग जोड़ने में विफल",
      failedToApprove: "उपयोगकर्ता को स्वीकृत करने में विफल",
      failedToReject: "उपयोगकर्ता को अस्वीकार करने में विफल",
      userApproved: "उपयोगकर्ता सफलतापूर्वक स्वीकृत",
      userRejected: "उपयोगकर्ता अस्वीकारित",
      delete: "हटाएं",
    },
    farmer: {
      welcome: "स्वागत है",
      manageFarm: "अपनी खेती की गतिविधियों और फसलों का प्रबंधन करें",
      logout: "लॉगआउट",
      marketDemand: "बाजार मांग",
      latestDemand: "एडमिन द्वारा साझा की गई नवीनतम मांग",
      refresh: "रीफ्रेश",
      loadingDemand: "बाजार मांग लोड हो रही है...",
      noDemand: "अभी बाजार मांग उपलब्ध नहीं है।",
      noImage: "कोई छवि उपलब्ध नहीं",
      crop: "फसल",
      region: "क्षेत्र",
      demandLevel: "मांग स्तर",
      season: "मौसम",
      quantity: "मात्रा",
      price: "मूल्य",
      revenueGenerate: "राजस्व अनुमान उत्पन्न करें",
      accountInfo: "खाता जानकारी",
      nameLabel: "नाम",
      emailLabel: "ईमेल",
      phoneLabel: "फोन",
      addressLabel: "पता",
      seasonLabel: "मौसम",
      quantityLabel: "मात्रा",
      pricePerUnit: "प्रति इकाई मूल्य",
      regionLabel: "क्षेत्र",
      estimateRevenue: "इस फसल के लिए राजस्व का अनुमान लगाएं",
    },
  },
};

const LanguageContext = createContext(null);

const languages = ["en", "te", "hi"];

const getNestedValue = (obj, path) =>
  path
    .split(".")
    .reduce(
      (acc, key) => (acc && acc[key] !== undefined ? acc[key] : null),
      obj,
    );

export const LanguageProvider = ({ children }) => {
  const initialLanguage =
    typeof window !== "undefined" && localStorage.getItem(STORAGE_KEY)
      ? localStorage.getItem(STORAGE_KEY)
      : "en";

  const [language, setLanguageState] = useState(
    languages.includes(initialLanguage) ? initialLanguage : "en",
  );

  const setLanguage = (nextLanguage) => {
    if (!languages.includes(nextLanguage)) {
      return;
    }
    setLanguageState(nextLanguage);
    localStorage.setItem(STORAGE_KEY, nextLanguage);
  };

  const cycleLanguage = () => {
    const currentIndex = languages.indexOf(language);
    const nextLanguage = languages[(currentIndex + 1) % languages.length];
    setLanguage(nextLanguage);
  };

  const t = (key) => {
    const localizedText = getNestedValue(translations[language], key);
    if (localizedText !== null) {
      return localizedText;
    }
    const fallbackText = getNestedValue(translations.en, key);
    return fallbackText !== null ? fallbackText : key;
  };

  const value = useMemo(
    () => ({ language, setLanguage, cycleLanguage, t, languages }),
    [language],
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
